export const GET_SIGNATRUE = "GET_SIGNATRUE"
export const GET_SIGNATRUE_SUCCESS = "GET_SIGNATRUE_SUCCESS"
export const GET_SIGNATRUE_ERROR = "GET_SIGNATRUE_ERROR"

export const PAYMENT = "PAYMENT"
export const PAYMENT_ERROR = "PAYMENT_ERROR"
export const PAYMENT_SUCCESS = "PAYMENT_SUCCESS"